/* Automatically generated by configure - do not modify! */

#ifndef XINELIBOUTPUT_FEATURES_H
#define XINELIBOUTPUT_FEATURES_H

#undef  HAVE_X11
#undef  HAVE_FB
#define HAVE_VDR 1
#undef  HAVE_LIBXINE
#undef  HAVE_LIBEXTRACTOR
#undef  HAVE_LIBAVUTIL
#undef  HAVE_LIBJPEG
#undef  HAVE_DBUS_GLIB_1
#undef  HAVE_XSHM
#undef  HAVE_XDPMS
#undef  HAVE_XINERAMA
#undef  HAVE_XRENDER
#undef  HAVE_XSHAPE
#undef  HAVE_OPENGL
#undef  HAVE_PTHREAD
#define HAVE_DLFCN 1
#undef  HAVE_VDPAU
#define HAVE_I18N 1
#define HAVE_LIBCAP 1

#endif /* XINELIBOUTPUT_FEATURES_H */
