#!/bin/sh
# zen2vdr - a VDR microdistribution based on gentoo linux
# Copyright (C) <2008-2011>  D.Herrendoerfer. 
# Distributed under the terms of the GPLv2

echo -n "CLOCK: "

start() {
echo -n "set "
/sbin/hwclock --hctosys

# If the BIOS time was cleared advance it
[ $(date +%Y) -lt 1990 ] && ( date 010101002000 > /dev/null )
}

stop() {
echo -n "save "
/sbin/hwclock --systohc
}

restart() {
stop
start
}

case "$1" in
  start)
  	start
	;;
  stop)
  	stop
	;;
  restart|reload)
  	restart
	;;
  *)
	echo $"Usage: $0 {start|stop|restart}"
	exit 1
esac

echo "OK"

exit $?
