#!/bin/sh
# zen2vdr - a VDR microdistribution based on gentoo linux
# Copyright (C) <2008-2011>  D.Herrendoerfer. 
# Distributed under the terms of the GPLv2

echo -n "SMT: "

start() {
echo -n "fs454 "
/usr/sbin/fs454tool

echo -n "stv6421 "
/usr/sbin/stv6421tool -o

echo -n "lircd "
touch /dev/lircd
/usr/sbin/smtlircd

echo -n "irexec "
/usr/bin/irexec /etc/irexec.conf &

echo -n "fanmon "
/etc/smt-fanmon.sh &

echo -n "ready "
/usr/sbin/smt-ready
}

stop() {
echo -n "irexec "
killall irexec

echo -n "lircd "
killall smtlircd

echo -n "fanmon "
killall smt-fanmon.sh
}

restart() {
stop
start
}

case "$1" in
  start)
  	start
	;;
  stop)
  	stop
	;;
  restart|reload)
  	restart
	;;
  *)
	echo $"Usage: $0 {start|stop|restart}"
	exit 1
esac

echo "OK"

exit $?
